"""AI boilerplate detection rule.

This module provides rules to detect AI boilerplate and
template code in source files.
"""

import re
from pathlib import Path
from typing import List

from prefact.models import Fix, Issue, Severity, ValidationResult

try:
    from prefact.rules import BaseRule, register
except ImportError:
    from ..rules import BaseRule, register


@register
class AIBoilerplateRule(BaseRule):
    """Detect AI boilerplate and template code."""

    rule_id = "ai-boilerplate"
    description = "Detect AI boilerplate and template code"

    def _get_boilerplate_patterns(self) -> List[tuple[str, str]]:
        """Retrieve the list of boilerplate patterns and their messages."""
        return [
            (r"# (Copyright|License|MIT)", "boilerplate copyright"),
            # (r"# Author: .*(AI|ChatGPT|Claude|Bard)", "AI author attribution"),
            # (r"# Generated by .*AI", "AI generation attribution"),
            (r"def main\(\):", "standalone main function"),
            (r"if __name__ == ['\"]__main__['\"]:", "module execution block"),
        ]

    def _check_line(
        self, line_num: int, line: str, patterns: List[tuple[str, str]]
    ) -> List[Issue]:
        """Check a single line against boilerplate patterns and return any issues found."""
        issues = []
        for pattern, message in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                issues.append(
                    Issue(
                        rule_id=self.rule_id,
                        file=None,  # Will be set in scan_file
                        line=line_num,
                        col=0,
                        message=message,
                        severity=Severity.INFO,
                        original=line.strip(),
                    )
                )
        return issues

    def scan_file(self, path: Path, source: str) -> List[Issue]:
        issues = []

        patterns = self._get_boilerplate_patterns()
        lines = source.splitlines()
        for line_num, line in enumerate(lines, 1):
            line_issues = self._check_line(line_num, line, patterns)
            for issue in line_issues:
                issue.file = path  # Set the file path here
            issues.extend(line_issues)

        return issues

    def fix(
        self, path: Path, source: str, issues: List[Issue]
    ) -> tuple[str, List[Fix]]:
        # Boilerplate removal requires manual decision
        return source, []

    def validate(self, path: Path, original: str, fixed: str) -> ValidationResult:
        return self._validate_by_rescan(
            path, original, fixed, "no_boilerplate", "Still has {count} boilerplate"
        )
