"""Tests for TODO.md ownership: prefact manages only its own block."""

from pathlib import Path

import pytest

from prefact.autonomous.todo_manager import (
    PREFACT_BEGIN,
    PREFACT_END,
    TodoManager,
)

MANUAL_PLAN = """<!-- KORU-AUTONOMY-PLAN:START — sekcja ręczna -->
## 🎯 Plan działań: autonomia i determinizm

- [ ] **P0-2** Trwały manifest runu
- [x] **P0-1** Accept ADR-005
<!-- KORU-AUTONOMY-PLAN:END -->"""

LEGACY_TODO = f"""# TODO

**Generated by:** prefact v0.1.67
**Generated on:** 2026-07-18T19:45:58
**Total issues:** 2 active, 1 completed

---

{MANUAL_PLAN}

## ✅ Completed Tasks

- [x] src/pkg/old.py:5 - Unused import: 'os'

## 📋 Current Issues (showing 2 of 2)

- [ ] src/pkg/a.py:10 - Unused import: 'sys'
- [ ] src/pkg/b.py:20 - String concatenation can be converted to f-string

---

*To execute all tasks, run: `prefact -a --execute-todos`*"""


@pytest.fixture()
def manager(tmp_path: Path) -> TodoManager:
    mgr = TodoManager(tmp_path)
    mgr.issues_found = [
        {
            "file": str(tmp_path / "src/pkg/a.py"),
            "examples": [{"line": 10, "message": "Unused import: 'sys'"}],
        }
    ]
    return mgr


def _write(mgr: TodoManager, text: str) -> None:
    mgr.todo_path.write_text(text)


class TestLegacyMigration:
    def test_manual_section_survives_regeneration(self, manager):
        _write(manager, LEGACY_TODO)
        manager.update_todo_md()
        out = manager.todo_path.read_text()
        assert "KORU-AUTONOMY-PLAN:START" in out
        assert "- [ ] **P0-2** Trwały manifest runu" in out
        assert PREFACT_BEGIN in out and PREFACT_END in out

    def test_manual_checkboxes_are_not_adopted_as_tickets(self, manager):
        _write(manager, LEGACY_TODO)
        manager.update_todo_md()
        out = manager.todo_path.read_text()
        # the manual checkbox must appear exactly once, unchanged (not "completed")
        assert out.count("- [ ] **P0-2** Trwały manifest runu") == 1
        assert "- [x] **P0-2**" not in out
        owned = out.split(PREFACT_BEGIN, 1)[1].split(PREFACT_END, 1)[0]
        assert "P0-2" not in owned

    def test_prefact_tickets_still_tracked_across_migration(self, manager):
        _write(manager, LEGACY_TODO)
        manager.update_todo_md()
        out = manager.todo_path.read_text()
        owned = out.split(PREFACT_BEGIN, 1)[1].split(PREFACT_END, 1)[0]
        # a.py issue still active; b.py issue gone → moved to completed
        assert "- [ ] src/pkg/a.py:10 - Unused import: 'sys'" in owned
        assert "- [x] src/pkg/b.py:20" in owned

    def test_file_without_prefact_content_is_fully_preserved(self, manager):
        _write(manager, "# My own notes\n\n- [ ] my manual task\n")
        manager.update_todo_md()
        out = manager.todo_path.read_text()
        assert "# My own notes" in out
        assert "- [ ] my manual task" in out
        assert PREFACT_BEGIN in out


class TestMarkerFiles:
    def test_rewrite_touches_only_the_block(self, manager):
        _write(
            manager,
            f"# Top notes\n\n{PREFACT_BEGIN}\nstale generated stuff\n{PREFACT_END}\n\n"
            f"{MANUAL_PLAN}\n",
        )
        manager.update_todo_md()
        out = manager.todo_path.read_text()
        assert "# Top notes" in out
        assert "stale generated stuff" not in out
        assert "- [ ] **P0-2** Trwały manifest runu" in out
        assert out.index("# Top notes") < out.index(PREFACT_BEGIN)
        assert out.index(PREFACT_END) < out.index("KORU-AUTONOMY-PLAN:START")

    def test_repeated_runs_do_not_duplicate_manual_content(self, manager):
        _write(manager, LEGACY_TODO)
        manager.update_todo_md()
        manager.update_todo_md()
        manager.update_todo_md()
        out = manager.todo_path.read_text()
        assert out.count("KORU-AUTONOMY-PLAN:START") == 1
        assert out.count(PREFACT_BEGIN) == 1
        assert out.count("- [ ] **P0-2** Trwały manifest runu") == 1

    def test_parse_todo_tasks_ignores_manual_checkboxes(self, manager):
        _write(
            manager,
            f"- [ ] src/pkg/manual.py:1 - Fake manual entry\n\n"
            f"{PREFACT_BEGIN}\n## 📋 Current Issues\n\n"
            f"- [ ] src/pkg/a.py:10 - Unused import: 'sys'\n{PREFACT_END}\n",
        )
        tasks = manager._parse_todo_tasks()
        assert [(t["file"], t["line"]) for t in tasks] == [("src/pkg/a.py", 10)]


class TestExecutionResults:
    def test_execution_summary_preserves_manual_content(self, manager):
        _write(manager, LEGACY_TODO)
        manager._update_todo_with_execution_results(
            completed_tasks=["- [x] src/pkg/a.py:10 - Unused import: 'sys' ✅"],
            executed_count=1,
            processed_tasks=1,
            total_tasks=1,
        )
        out = manager.todo_path.read_text()
        assert "- [ ] **P0-2** Trwały manifest runu" in out
        assert "## 📋 Task Status" in out
        assert PREFACT_BEGIN in out
