"""Focused regression tests for TODO.md ownership and rendering submodules."""

from prefact.autonomous.todo_ownership import (
    PREFACT_BEGIN,
    PREFACT_END,
    classify_legacy_lines,
    split_existing,
    split_legacy,
)
from prefact.autonomous.todo_render import build_execution_block, build_todo_block

LEGACY_TODO = """# TODO

**Generated by:** prefact v0.1.67
**Generated on:** 2026-07-18T19:45:58
**Total issues:** 2 active, 1 completed

---

<!-- MANUAL:START -->
- [ ] manual item
<!-- MANUAL:END -->

## ✅ Completed Tasks

- [x] src/pkg/old.py:5 - Unused import: 'os'

## 📋 Current Issues (showing 2 of 2)

- [ ] src/pkg/a.py:10 - Unused import: 'sys'
- [ ] src/pkg/b.py:20 - String concatenation can be converted to f-string

---

*To execute all tasks, run: `prefact -a --execute-todos`*"""


class TestClassifyLegacyLines:
    def test_generated_header_is_owned(self):
        lines = ["# TODO", "", "**Generated by:** prefact v1.0", "**Generated on:** x", "---"]
        assert classify_legacy_lines(lines) == [True, True, True, True, True]

    def test_plain_todo_heading_is_manual(self):
        lines = ["# TODO", "", "my own note"]
        assert classify_legacy_lines(lines) == [False, False, False]

    def test_owned_sections_and_their_bodies(self):
        lines = [
            "## ✅ Completed Tasks",
            "",
            "- [x] a.py:1 - fixed",
            "## 📋 Current Issues (showing 2 of 2)",
            "- [ ] b.py:2 - issue",
        ]
        assert classify_legacy_lines(lines) == [True, True, True, True, True]

    def test_boundary_comment_closes_owned_section(self):
        lines = [
            "## 📋 Current Issues",
            "- [ ] b.py:2 - issue",
            "<!-- MANUAL:START -->",
            "- [ ] manual item",
        ]
        assert classify_legacy_lines(lines) == [True, True, False, False]

    def test_footer_claims_separator_above_it(self):
        lines = [
            "trailing manual note",
            "",
            "---",
            "",
            "*To execute all tasks, run: `prefact -a --execute-todos`*",
        ]
        assert classify_legacy_lines(lines) == [
            False,  # manual note
            False,  # blank above the separator stays manual
            True,  # ---
            True,  # blank
            True,  # footer
        ]

    def test_section_claims_lines_until_boundary(self):
        lines = [
            "## 📋 Current Issues",
            "- [ ] b.py:2 - issue",
            "still owned (no boundary yet)",
            "<!-- MANUAL:START -->",
            "manual item",
        ]
        assert classify_legacy_lines(lines) == [True, True, True, False, False]

    def test_no_prefact_content_means_all_manual(self):
        lines = ["# My notes", "- [ ] my task"]
        assert not any(classify_legacy_lines(lines))


class TestSplitLegacy:
    def test_manual_plan_moves_after_owned_block(self):
        before, owned, after = split_legacy(LEGACY_TODO)
        # Header at line 0 → nothing before the owned region.
        assert before == ""
        assert "**Generated by:** prefact" in owned
        assert "## 📋 Current Issues (showing 2 of 2)" in owned
        assert "- [ ] src/pkg/a.py:10 - Unused import: 'sys'" in owned
        # Manual content outside the historically generated regions survives.
        assert "<!-- MANUAL:START -->" in after
        assert "- [ ] manual item" in after
        assert "MANUAL" not in owned

    def test_fully_manual_file_returns_empty_owned(self):
        before, owned, after = split_legacy("# Notes\n\n- [ ] mine\n")
        assert owned == "" and after == ""
        assert "# Notes" in before


class TestSplitExisting:
    def test_marker_block_round_trip(self):
        text = f"# Top\n\n{PREFACT_BEGIN}\nowned body\n{PREFACT_END}\n\n# Bottom\n"
        before, owned, after = split_existing(text)
        assert before == "# Top\n\n"
        assert owned == "\nowned body\n"
        assert after == "\n\n# Bottom\n"

    def test_marker_variant_prefix_is_matched(self):
        text = "# Top\n<!-- PREFACT:BEGIN older wording -->\nowned\n<!-- PREFACT:END -->\ntail"
        before, owned, after = split_existing(text)
        assert before == "# Top\n"
        assert owned.strip() == "owned"
        assert "tail" in after


class TestRenderBlocks:
    def test_build_todo_block_counts_and_footer(self):
        block = build_todo_block(
            ["- [ ] a.py:1 - msg"], ["- [x] b.py:2 - done"], 2, 3
        )
        assert "**Total issues:** 2 active, 3 completed" in block
        assert "## ✅ Completed Tasks (showing 1 of 3)" in block
        assert "## 📋 Current Issues (showing 1 of 2)" in block
        assert block.endswith("*To execute all tasks, run: `prefact -a --execute-todos`*")

    def test_build_execution_block_reports_processed_counts(self):
        block = build_execution_block(
            ["- [x] a.py:1 - msg ✅"], executed_count=1, processed_tasks=2, total_tasks=4
        )
        assert "**Total issues:** 2 processed of 4 active, 1 fixed" in block
        assert "**Last executed:**" in block
        assert "## 📋 Task Status" in block
