flowchart TD
    Taskfile["Taskfile<br/>1 funcs"]
    benchmark_ram_optimization["benchmark_ram_optimization<br/>5 funcs"]
    examples__01_individual_rules["examples.01-individual-rules<br/>38 funcs"]
    examples__02_multiple_rules["examples.02-multiple-rules<br/>4 funcs"]
    examples__03_output_formats["examples.03-output-formats<br/>2 funcs"]
    examples__04_custom_rules["examples.04-custom-rules<br/>7 funcs"]
    examples__06_api_usage["examples.06-api-usage<br/>4 funcs"]
    examples__sample_project["examples.sample-project<br/>18 funcs"]
    project__map["project.map<br/>2716 funcs"]
    src__prefact["src.prefact<br/>647 funcs"]
    vscode_extension__src["vscode-extension.src<br/>48 funcs"]
    src__prefact ==>|46| vscode_extension__src
    src__prefact ==>|43| Taskfile
    examples__06_api_usage ==>|34| Taskfile
    benchmark_ram_optimization ==>|25| Taskfile
    src__prefact ==>|23| project__map
    examples__sample_project ==>|17| Taskfile
    examples__01_individual_rules ==>|6| Taskfile
    examples__02_multiple_rules ==>|6| Taskfile
    examples__01_individual_rules -->|2| examples__sample_project
    examples__01_individual_rules -->|2| project__map
    examples__03_output_formats -->|2| Taskfile
    benchmark_ram_optimization -->|1| vscode_extension__src
    examples__sample_project -->|1| examples__01_individual_rules
    examples__sample_project -->|1| project__map
    examples__04_custom_rules -->|1| vscode_extension__src
