"""TODO.md ownership: splitting a document into manual and owned regions.

Ownership contract: prefact owns ONLY the block between ``PREFACT_BEGIN`` and
``PREFACT_END`` markers in TODO.md. Everything outside those markers is
operator-maintained content (action plans, notes, manual checklists) and is
preserved verbatim on every rewrite.

Legacy TODO.md files (written before the markers existed) are migrated on the
first rewrite: the generated header and the known prefact sections are
recognised as owned, everything else is kept as manual content, and the new
file wraps the owned part in markers.
"""

from typing import List, Tuple

PREFACT_BEGIN = "<!-- PREFACT:BEGIN — generated block, edits inside will be overwritten -->"
PREFACT_END = "<!-- PREFACT:END -->"

# Section headings prefact has historically generated (legacy files only).
_OWNED_HEADINGS = (
    "## ✅ Completed Tasks",
    "## 📋 Current Issues",
    "## 📋 Task Status",
)

# Legacy generated-header signature, matched within a short lookahead.
_HEADER_SIGNATURE = "**Generated by:** prefact"
_HEADER_LOOKAHEAD = 6

_FOOTER_PREFIX = "*To execute all tasks"


def split_existing(text: str) -> Tuple[str, str, str]:
    """Return ``(before, owned, after)`` regions of a TODO.md document.

    ``owned`` is the only region prefact may parse or rewrite; ``before``
    and ``after`` are operator content preserved verbatim. Marker-less
    legacy documents are migrated via :func:`split_legacy`.
    """
    if PREFACT_BEGIN in text and PREFACT_END in text:
        before, rest = text.split(PREFACT_BEGIN, 1)
        owned, after = rest.split(PREFACT_END, 1)
        return before, owned, after
    # Marker variants from other versions: match on the stable prefix.
    if "<!-- PREFACT:BEGIN" in text and PREFACT_END in text:
        before, rest = text.split("<!-- PREFACT:BEGIN", 1)
        marker_rest = rest.split("-->", 1)
        owned, after = (marker_rest[1] if len(marker_rest) > 1 else rest).split(
            PREFACT_END, 1
        )
        return before, owned, after
    return split_legacy(text)


def split_legacy(text: str) -> Tuple[str, str, str]:
    """Split a pre-marker TODO.md into manual and prefact-owned parts."""
    lines = text.split("\n")
    flags = classify_legacy_lines(lines)
    if not any(flags):
        # Nothing recognisably prefact-generated: whole file is manual.
        return text, "", ""
    first_owned = flags.index(True)
    before = "\n".join(lines[:first_owned])
    owned = "\n".join(
        line for line, flag in zip(lines[first_owned:], flags[first_owned:]) if flag
    )
    after = "\n".join(
        line
        for line, flag in zip(lines[first_owned:], flags[first_owned:])
        if not flag
    )
    return before, owned, after


def classify_legacy_lines(lines: List[str]) -> List[bool]:
    """Flag lines that belong to prefact-generated content (legacy files)."""
    flags = [False] * len(lines)
    mode: str | None = None  # "header" | "section" | None
    for idx, line in enumerate(lines):
        stripped = line.strip()
        if mode is not None:
            if _is_boundary_line(stripped):
                mode = None  # boundary — reclassify this line below
            else:
                flags[idx] = True
                if mode == "header" and stripped == "---":
                    mode = None
                continue
        if stripped == "# TODO":
            if _has_prefact_signature(lines, idx):
                flags[idx] = True
                mode = "header"
            continue
        if _is_owned_heading(stripped):
            flags[idx] = True
            mode = "section"
            continue
        if stripped.startswith(_FOOTER_PREFIX):
            _claim_footer(lines, flags, idx)
    return flags


def _is_boundary_line(stripped: str) -> bool:
    """A heading or comment line closes the current owned region."""
    return stripped.startswith("## ") or stripped.startswith("<!--")


def _has_prefact_signature(lines: List[str], idx: int) -> bool:
    """Detect the generated header below a ``# TODO`` heading."""
    lookahead = [lines[j].strip() for j in range(idx, min(idx + _HEADER_LOOKAHEAD, len(lines)))]
    return any(la.startswith(_HEADER_SIGNATURE) for la in lookahead)


def _is_owned_heading(stripped: str) -> bool:
    """Match one of the section headings prefact has historically generated."""
    return any(stripped.startswith(heading) for heading in _OWNED_HEADINGS)


def _claim_footer(lines: List[str], flags: List[bool], idx: int) -> None:
    """Claim the execute-footer plus the blank/``---`` separator above it."""
    flags[idx] = True
    j = idx - 1
    while j >= 0 and not lines[j].strip():
        flags[j] = True
        j -= 1
    if j >= 0 and lines[j].strip() == "---":
        flags[j] = True
