"""Render the prefact-owned TODO.md block content."""

from datetime import datetime
from typing import List

from prefact import __version__


def build_todo_block(
    new_todos: List[str],
    completed_tasks: List[str],
    total_active_todos: int,
    total_completed_todos: int,
) -> str:
    """Build the regenerated prefact block for TODO.md."""
    content = "# TODO\n\n"
    content += f"**Generated by:** prefact v{__version__}\n"
    content += f"**Generated on:** {datetime.now().isoformat()}\n"
    content += f"**Total issues:** {total_active_todos} active, {total_completed_todos} completed\n\n"
    content += "---\n\n"

    # Add completed tasks first
    if completed_tasks:
        content += "## ✅ Completed Tasks"
        if total_completed_todos > len(completed_tasks):
            content += f" (showing {len(completed_tasks)} of {total_completed_todos})"
        content += "\n\n"
        content += "\n".join(completed_tasks)
        content += "\n\n"

    # Add current tasks
    if new_todos:
        content += "## 📋 Current Issues"
        if total_active_todos > len(new_todos):
            content += f" (showing {len(new_todos)} of {total_active_todos})"
        content += "\n\n"
        content += "\n".join(new_todos)
        content += "\n\n---\n\n*To execute all tasks, run: `prefact -a --execute-todos`*"

    return content


def build_execution_block(
    completed_tasks: List[str],
    executed_count: int,
    processed_tasks: int,
    total_tasks: int,
) -> str:
    """Build the prefact block written after executing TODO tasks."""
    new_content = "# TODO\n\n"
    new_content += f"**Generated by:** prefact v{__version__}\n"
    new_content += f"**Generated on:** {datetime.now().isoformat()}\n"
    new_content += f"**Last executed:** {datetime.now().isoformat()}\n"
    new_content += f"**Total issues:** {processed_tasks} processed of {total_tasks} active, {executed_count} fixed\n\n"
    new_content += "---\n\n"

    if completed_tasks:
        new_content += "## 📋 Task Status\n\n"
        new_content += "\n".join(completed_tasks)
        new_content += "\n\n"

    return new_content
